apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runners.fullname" . }}-secrets
  labels:
    {{- include "runners.labels" . | nindent 4 }}
data:
  kaniko.json: {{ .Files.Get "files/kaniko.json" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runners.fullname" . }}-registry-compredict
  labels:
    {{- include "runners.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Files.Get "files/kaniko.json" | b64enc }}
type: kubernetes.io/dockerconfigjson
