apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-from-runners
  namespace: compredict
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: maintainer
subjects:
- kind: ServiceAccount
  name: compredict-deploy
  namespace: arc-runners
- kind: ServiceAccount
  name: compredict-deploy
  namespace: github-runners
- kind: ServiceAccount
  name: compredict-deploy
  namespace: my-runners
