---
apiVersion: v1
data:
  github_token: {{ required "global.secret.asisakov_github_token_fine is required" .Values.global.secret.asisakov_github_token_fine }}
kind: Secret
metadata:
  name: github-token-fine
  namespace: github-runners
  labels:
    helm.sh/chart: "{{ .Chart.Name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
---
apiVersion: v1
data:
  github_token: {{ required "global.secret.peter_sh_github_token_fine is required" .Values.global.secret.peter_sh_github_token_fine }}
kind: Secret
metadata:
  name: github-token-fine
  namespace: my-runners
  labels:
    helm.sh/chart: "{{ .Chart.Name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
