apiVersion: v1
kind: Service
metadata:
  name: {{ include "front.fullname" . }}
  labels: {{- include "front.labels" . | nindent 4 }}
spec:
  selector: {{- include "front.selectorLabels" . | nindent 4 }}
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 8080
