apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
    contentHash: {{ .Values.contentHash }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
        contentHash: {{ .Values.contentHash }}
        log_format: unordered
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: r.compredict.xyz/api:latest
          args:
            - --host
            - 0.0.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
              name: api-port
          env:
            - name: CLICKHOUSE_PORT
              valueFrom:
                configMapKeyRef:
                  name: compredict-config
                  key: CLICKHOUSE_PORT
            - name: CLICKHOUSE_HOST
              valueFrom:
                configMapKeyRef:
                  name: compredict-config
                  key: CLICKHOUSE_HOST
            - name: CLICKHOUSE_USER
              valueFrom:
                configMapKeyRef:
                  name: compredict-config
                  key: CLICKHOUSE_USER_RO
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: compredict-secrets
                  key: CLICKHOUSE_USER_RO_PASSWORD
      imagePullSecrets:
        - name: registry-compredict
