apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels: {{- include "api.labels" . | nindent 4 }}
spec:
  selector: {{- include "api.selectorLabels" . | nindent 4 }}
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 8000
