apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry
spec:
  storageClassName: local-storage
  volumeName: registry
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

